"""
Financial data normalization utilities.
Handles cleaning numbers, detecting formats, and annualizing data.
"""

import re
from typing import Optional, Dict, Any
from decimal import Decimal, InvalidOperation

from ..infrastructure.logging import get_logger

logger = get_logger(__name__)


class FinancialNormalizer:
    """Normalizes financial data from various formats."""
    
    # Common financial field synonyms
    FIELD_SYNONYMS = {
        'revenue': [
            'net sales', 'total net sales', 'revenue', 'total revenue', 
            'sales', 'total sales', 'turnover'
        ],
        'cogs': [
            'cost of sales', 'total cost of sales', 'cost of goods sold',
            'cost of revenue', 'cogs'
        ],
        'gross_profit': [
            'gross profit', 'gross margin', 'total gross profit'
        ],
        'opex': [
            'total operating expenses', 'operating expenses', 'total operating costs',
            'operating costs', 'sg&a', 'selling general and administrative'
        ],
        'rnd': [
            'research and development', 'r&d', 'research & development',
            'research development'
        ],
        'sga': [
            'sales, general and administrative', 'selling, general and administrative',
            'sg&a', 'sales, general & administrative'
        ],
        'operating_income': [
            'operating income', 'income from operations', 'operating profit',
            'ebit'
        ],
        'ebitda': [
            'ebitda', 'earnings before interest taxes depreciation amortization'
        ],
        'net_income': [
            'net income', 'net earnings', 'net profit', 'net loss',
            'net income (loss)', 'net earnings (loss)'
        ],
        'interest_expense': [
            'interest expense', 'interest and dividend income', 'interest income'
        ],
        'taxes': [
            'provision for income taxes', 'income tax expense', 'income tax',
            'tax expense'
        ],
        'depreciation': [
            'depreciation and amortization', 'depreciation', 'd&a'
        ],
        'cash': [
            'cash and cash equivalents', 'cash, cash equivalents and marketable securities',
            'cash and cash equivalents, end of period', 'cash'
        ],
        'total_assets': [
            'total assets', 'assets'
        ],
        'total_liabilities': [
            'total liabilities', 'liabilities'
        ],
        'total_equity': [
            'shareholders\' equity', 'total shareholders\' equity',
            'total equity', 'stockholders\' equity'
        ],
        'short_term_debt': [
            'short-term debt', 'current portion of long-term debt',
            'commercial paper', 'loans payable, net, current',
            'notes payable, current', 'current debt'
        ],
        'long_term_debt': [
            'long-term debt', 'long term debt', 'term debt',
            'loans payable, net, non-current', 'notes payable, non-current',
            'non-current debt'
        ],
        'accounts_receivable': [
            'accounts receivable, net', 'accounts receivable'
        ],
        'inventory': [
            'inventories', 'inventory'
        ],
        'accounts_payable': [
            'accounts payable'
        ],
        'cfo': [
            'net cash provided by operating activities',
            'net cash used in operating activities',
            'cash generated by operating activities',
            'cash from operations', 'cash flows from operating activities'
        ],
        'capex': [
            'purchases related to property and equipment and intangible assets',
            'payments for acquisition of property, plant and equipment',
            'capital expenditures', 'purchases of property and equipment',
            'purchase of property and equipment', 'acquisitions of property, plant and equipment'
        ],
        'dividends': [
            'dividends paid', 'payments for dividends'
        ],
        'share_repurchases': [
            'payments related to repurchases of common stock',
            'repurchases of common stock'
        ],
    }
    
    @classmethod
    def clean_number(cls, text: str) -> Optional[float]:
        """
        Convert text to float, handling various financial formats.
        
        Handles:
        - Commas as thousand separators
        - Dollar signs
        - Parentheses for negative numbers
        - Percentages (returns decimal)
        - Abbreviations (K, M, B)
        
        Args:
            text: String to convert
            
        Returns:
            Float value or None if conversion fails
        """
        if not text or not isinstance(text, str):
            return None
        
        text = text.strip()
        
        if not text or text == '-':
            return None
        
        try:
            # Check for parentheses indicating negative
            is_negative = '(' in text and ')' in text
            
            # Check for percentage
            is_percentage = '%' in text
            
            # Check for abbreviations
            multiplier = 1.0
            upper = text.upper()
            if upper.endswith('K'):
                multiplier = 1e3
            elif upper.endswith('M'):
                multiplier = 1e6
            elif upper.endswith('B'):
                multiplier = 1e9
            
            # Remove all non-numeric characters except decimal point and minus
            cleaned = re.sub(r'[^0-9.-]', '', text)
            
            if not cleaned:
                return None
            
            # Parse number
            value = float(cleaned)
            
            # Apply modifiers
            if is_negative:
                value = -abs(value)
            
            if is_percentage:
                value = value / 100.0
            
            value = value * multiplier
            
            return value
            
        except (ValueError, InvalidOperation) as e:
            logger.debug("number_parse_failed", text=text, error=str(e))
            return None
    
    @classmethod
    def detect_quarterly_data(cls, markdown_content: str) -> bool:
        """
        Detect if financial data is quarterly based on headers.
        
        Args:
            markdown_content: Raw markdown from extraction
            
        Returns:
            True if quarterly data detected
        """
        quarterly_patterns = [
            r'three\s+months\s+ended',
            r'quarterly',
            r'q[1-4]\s+(?:fy|fiscal)',
            r'13\s+weeks\s+ended'
        ]
        
        content_lower = markdown_content.lower()
        
        for pattern in quarterly_patterns:
            if re.search(pattern, content_lower):
                logger.info("quarterly_data_detected", pattern=pattern)
                return True
        
        return False
    
    @classmethod
    def annualize(cls, value: float, is_quarterly: bool) -> float:
        """
        Annualize quarterly financial data.
        
        Args:
            value: Financial value
            is_quarterly: Whether data is quarterly
            
        Returns:
            Annualized value
        """
        if not is_quarterly or value is None:
            return value
        
        return value * 4.0
    
    @classmethod
    def find_field_value(
        cls,
        data_map: Dict[str, str],
        field_name: str,
        default: Optional[float] = None
    ) -> Optional[float]:
        """
        Find value in data map using field synonyms.
        
        Args:
            data_map: Dictionary of extracted values
            field_name: Name of field to find
            default: Default value if not found
            
        Returns:
            Found value or default
        """
        synonyms = cls.FIELD_SYNONYMS.get(field_name, [field_name])
        
        # Try exact match first
        for synonym in synonyms:
            term = synonym.lower()
            if term in data_map:
                val = cls.clean_number(data_map[term])
                if val is not None:
                    return val
        
        # Try substring match
        for synonym in synonyms:
            term = synonym.lower()
            for key, val_str in data_map.items():
                if term in key.lower():
                    val = cls.clean_number(val_str)
                    if val is not None:
                        return val
        
        return default
