"""
Integration tests for the refactored system.
"""

import pytest
from unittest.mock import Mock, patch

from counterfactual_oracle.src.models import (
    FinancialReport, IncomeStatement, BalanceSheet, CashFlow,
    ScenarioParams, AggregatedSimulation, SimulationResult
)
from counterfactual_oracle.src.parsers.mapper import FinancialMapper
from counterfactual_oracle.src.parsers.validator import ExtractionValidator


class TestEndToEndFlow:
    """Test the complete data flow."""
    
    @pytest.fixture
    def sample_raw_landing_ai_response(self):
        """Create a sample Landing AI response."""
        return {
            "markdown": """
            # CONSOLIDATED STATEMENTS OF OPERATIONS
            <table>
            <tr><td>Total net sales</td><td>119,575</td></tr>
            <tr><td>Cost of sales</td><td>64,720</td></tr>
            <tr><td>Gross profit</td><td>54,855</td></tr>
            <tr><td>Total operating expenses</td><td>14,482</td></tr>
            <tr><td>Operating income</td><td>40,373</td></tr>
            <tr><td>Net income</td><td>30,000</td></tr>
            </table>
            
            # CONSOLIDATED BALANCE SHEETS
            <table>
            <tr><td>Total assets</td><td>300,000</td></tr>
            <tr><td>Total liabilities</td><td>100,000</td></tr>
            <tr><td>Total shareholders' equity</td><td>200,000</td></tr>
            <tr><td>Cash and cash equivalents</td><td>50,000</td></tr>
            </table>
            
            # CONSOLIDATED STATEMENTS OF CASH FLOWS
            <table>
            <tr><td>Net income</td><td>30,000</td></tr>
            <tr><td>Cash generated by operating activities</td><td>40,000</td></tr>
            <tr><td>Payments for property and equipment</td><td>(10,000)</td></tr>
            </table>
            """,
            "metadata": {
                "page_count": 10,
                "duration_ms": 2500,
                "credit_usage": 2.5,
                "job_id": "test-job-abc123"
            }
        }
    
    def test_extraction_to_validation_flow(self, sample_raw_landing_ai_response):
        """Test complete flow from extraction to validation."""
        # Step 1: Parse raw response
        mapper = FinancialMapper()
        report = mapper.parse_raw_response(sample_raw_landing_ai_response)
        
        # Step 2: Verify parsing worked
        assert report.income_statement.Revenue == 119575.0
        assert report.income_statement.CostOfGoodsSold == 64720.0
        assert report.income_statement.GrossProfit == 54855.0
        assert report.balance_sheet.Assets['TotalAssets'] == 300000.0
        assert report.balance_sheet.Cash == 50000.0
        assert report.cash_flow.CashFromOperations == 40000.0
        assert report.cash_flow.FreeCashFlow == 30000.0  # CFO(40,000) - CapEx(10,000)
        
        # Step 3: Validate the report
        validator = ExtractionValidator()
        validation_result = validator.validate(report)
        
        # Step 4: Check validation passed
        assert validation_result.is_valid is True
        assert len(validation_result.get_errors()) == 0
    
    def test_simulation_with_report(self, sample_raw_landing_ai_response):
        """Test simulation using parsed report."""
        from counterfactual_oracle.src.logic import run_monte_carlo
        
        # Parse report
        mapper = FinancialMapper()
        report = mapper.parse_raw_response(sample_raw_landing_ai_response)
        
        # Create scenario params
        params = ScenarioParams(
            opex_delta_bps=100,  # +1% OpEx
            revenue_growth_bps=200,  # +2% growth
            discount_rate_bps=0
        )
        
        # Run simulation (with fewer iterations for testing)
        results = run_monte_carlo(report, params, num_simulations=100)
        
        # Verify simulation produced results
        assert results.median_npv != 0
        assert results.median_revenue > 0
        assert results.median_ebitda > 0
        assert len(results.revenue_forecast_p50) == 5  # 5 years
        assert len(results.simulation_runs) == 100


class TestSecurityIntegration:
    """Test security features in context."""
    
    def test_file_upload_security(self, tmp_path):
        """Test secure file handling."""
        from counterfactual_oracle.src.infrastructure.security import (
            create_secure_temp_file,
            cleanup_temp_file,
            validate_file_size
        )
        
        # Create a mock uploaded file
        test_file = tmp_path / "test.pdf"
        test_file.write_text("PDF content here")
        
        # Mock the uploaded file object
        class MockUploadedFile:
            name = "../../../etc/passwd.pdf"  # Path traversal attempt
            def getbuffer(self):
                return b"PDF content"
        
        mock_file = MockUploadedFile()
        
        # Should sanitize filename
        temp_path, safe_name = create_secure_temp_file(mock_file)
        
        # Verify path traversal was prevented
        assert ".." not in safe_name
        assert safe_name.endswith(".pdf")
        assert "passwd" not in safe_name or "_" in safe_name
        
        # Cleanup
        cleanup_temp_file(temp_path)
        assert not temp_path.exists()


class TestCachingIntegration:
    """Test caching behavior."""
    
    def test_cache_decorator(self):
        """Test that caching works correctly."""
        from counterfactual_oracle.src.infrastructure.cache import cache
        
        call_count = 0
        
        @cache.cached(ttl=60)
        def expensive_function(x):
            nonlocal call_count
            call_count += 1
            return x * 2
        
        # First call should execute
        result1 = expensive_function(5)
        assert result1 == 10
        assert call_count == 1
        
        # Second call with same arg should use cache
        result2 = expensive_function(5)
        assert result2 == 10
        assert call_count == 1  # Not incremented
        
        # Different arg should execute
        result3 = expensive_function(10)
        assert result3 == 20
        assert call_count == 2


class TestConfigurationIntegration:
    """Test configuration system."""
    
    def test_settings_loading(self):
        """Test that settings load correctly."""
        from counterfactual_oracle.src.config import get_settings, validate_settings
        
        settings = get_settings()
        
        # Verify default values
        assert settings.monte_carlo_iterations == 10000
        assert settings.default_wacc == 0.08
        assert settings.forecast_years == 5
        assert settings.max_debate_rounds == 10
        
        # Validate settings
        missing = validate_settings()
        # In non-production, this should be empty or only warn
        assert isinstance(missing, list)


class TestTelemetryIntegration:
    """Test telemetry collection."""
    
    def test_metrics_recording(self):
        """Test that metrics are recorded."""
        from counterfactual_oracle.src.infrastructure.telemetry import (
            record_debate_metrics,
            record_simulation_metrics,
            DEBATE_ROUNDS,
            SIMULATION_RESULTS
        )
        
        # Record some metrics
        record_debate_metrics(converged=True, rounds=5, duration=10.5)
        record_simulation_metrics(iterations=10000, duration=2.5, median_npv=1000000)
        
        # Just verify no exceptions were raised
        # In real usage, these would be scraped by Prometheus


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
